h0=figure('toolbar','none',...
    'position',[198 56 350 468],...
    'name','过滤操作');
h1=axes('parent',h0,...
    'position',[0.3 0.45 0.5 0.5],...
    'visible','off');
I=imread('blood1.tif');
imshow(I)
b1=uicontrol('parent',h0,...
    'units','points',...
    'tag','b1',...
    'style','pushbutton',...
    'backgroundcolor',[0.75 0.75 0.75],...
    'string','均平过滤',...
    'position',[50 120 50 20],...
    'callback',[...
        'cla,',...
        'I=imread(''blood1.tif'');,',...
        'h=fspecial(''average'',6);,',...
        'I2=uint8(round(filter2(h,I)));,',...
        'imshow(I2)']);
b2=uicontrol('parent',h0,...
    'units','points',...
    'tag','b2',...
    'style','pushbutton',...
    'backgroundcolor',[0.75 0.75 0.75],...
    'string','Sobel过滤',...
    'position',[150 120 50 20],...
    'callback',[...
        'cla,',...
        'I=imread(''blood1.tif'');,',...
        'h=fspecial(''sobel'');,',...
        'I2=filter2(h,I);,',...
        'imshow(I2,[])']);
b1=uicontrol('parent',h0,...
    'units','points',...
    'tag','b1',...
    'style','pushbutton',...
    'backgroundcolor',[0.75 0.75 0.75],...
    'string','关闭',...
    'position',[85 60 80 30],...
    'callback','close');
