h0=figure('toolbar','none',...
    'position',[198 56 450 468],...
    'name','实例56');
h1=axes('parent',h0,...
    'position',[0.3 0.45 0.5 0.5],...
    'visible','off');
l1=uimenu(gcf,'label','Draw figure',...
    'tag','l1');
huidiao=[...
        'if get(r1,''value'')==1,',...
        'shading faceted,',...
        'end,',...
        'if get(r2,''value'')==1,',...
        'shading flat,',...
        'end,',...
        'if get(r3,''value'')==1,',...
        'shading interp,',...
        'end,',...
        'k=get(p1,''value'');,',...
        'switch k,',...
        'case 1,',...
        'colormap(''cool''),',...
        'case 2,',...
        'colormap(''spring''),',...
        'case 3,',...
        'colormap(''summer''),',...
        'case 4,',...
        'colormap(''autumn''),',...
        'case 5,',...
        'colormap(''winter''),',...
        'end'];
l11=uimenu('parent',l1,...
    'label','Surface',...
    'tag','l11',...
    'callback',[...
        '[x,y]=meshgrid(-8:0.5:8);,',...
        'r=sqrt(x.^2+y.^2)+eps;,',...
        'z=sin(r)./r;,',...
        'surf(x,y,z),',...
        huidiao]);
l12=uimenu('parent',l1,...
    'label','Mesh',...
    'tag','l12',...
    'callback',[...
        'mesh(peaks),',...
        huidiao]);
l13=uimenu('parent',l1,...
    'label','Membrane',...
    'tag','l13',...
    'callback',[...
        'mesh(membrane),',...
        huidiao]);
f1=uicontrol('parent',h0,...
    'units','points',...
    'listboxtop',0,...
    'position',[12 6 100 101],...
    'style','frame',...
    'tag','f1');
r1=uicontrol('parent',h0,...
    'units','points',...
    'backgroundcolor',[0.753 0.753 0.753],...
    'listboxtop',0,...
    'position',[19.5 58.5 72.75 16.5],...
    'string','shading faceted',...
    'style','radiobutton',...
    'tag','r1',...
    'value',1,...
    'callback',[...
        'shading faceted,',...
        'set(r1,''value'',1);,',...
        'set(r2,''value'',0);,',...
        'set(r3,''value'',0);']);
r2=uicontrol('parent',h0,...
    'units','points',...
    'backgroundcolor',[0.753 0.753 0.753],...
    'listboxtop',0,...
    'position',[19.5 35.25 78.75 18.75],...
    'string','shading flat',...
    'style','radiobutton',...
    'tag','r2',...
    'value',0,...
    'callback',[...
        'shading flat,',...
        'set(r2,''value'',1);,',...
        'set(r1,''value'',0);,',...
        'set(r3,''value'',0);']);
r3=uicontrol('parent',h0,...
    'units','points',...
    'backgroundcolor',[0.753 0.753 0.753],...
    'listboxtop',0,...
    'position',[19.5 12.75 71.25 18.75],...
    'string','shading interp',...
    'style','radiobutton',...
    'tag','r3',...
    'value',0,...
    'callback',[...
        'shading interp,',...
        'set(r3,''value'',1);,',...
        'set(r1,''value'',0);,',...
        'set(r2,''value'',0);']);
t1=uicontrol('parent',h0,...
    'units','points',...
    'backgroundcolor',[0.753 0.753 0.753],...
    'fontsize',12,...
    'listboxtop',0,...
    'position',[14.25 75.75 90.75 22.5],...
    'string','平滑处理',...
    'style','text',...
    'tag','t1');
t2=uicontrol('parent',h0,...
    'units','points',...
    'backgroundcolor',[0.753 0.753 0.753],...
    'fontsize',12,...
    'listboxtop',0,...
    'position',[117 69 72.75 17.5],...
    'string','设置色调',...
    'style','text',...
    'tag','t2');
p1=uicontrol('parent',h0,...
    'units','points',...
    'backgroundcolor',[0.753 0.753 0.753],...
    'listboxtop',0,...
    'position',[116.25 39 72.75 20.25],...
    'string','Cool|Spring|Summer|Autumn|Winter',...
    'style','popupmenu',...
    'tag','p1',...
    'value',1,...
    'callback',[...
        'k=get(p1,''value'');,',...
        'switch k,',...
        'case 1,',...
        'colormap(''cool''),',...
        'case 2,',...
        'colormap(''spring''),',...
        'case 3,',...
        'colormap(''summer''),',...
        'case 4,',...
        'colormap(''autumn''),',...
        'case 5,',...
        'colormap(''winter''),',...
        'end']);
b1=uicontrol('parent',h0,...
    'units','points',...
    'backgroundcolor',[0.753 0.753 0.753],...
    'listboxtop',0,...
    'position',[12 243 72.75 30.75],...
    'string','关闭',...
    'tag','b1',...
    'callback','close');
b2=uicontrol('parent',h0,...
    'units','points',...
    'backgroundcolor',[0.753 0.753 0.753],...
    'listboxtop',0,...
    'position',[216.75 67.5 83.25 18.75],...
    'string','Colorbar',...
    'tag','b2',...
    'callback','colorbar');