h0=figure('toolbar','none',...
    'position',[198 56 350 468],...
    'name','ÊµÀý67');
h1=axes('parent',h0,...
    'position',[0.2 0.45 0.6 0.5],...
    'visible','off');
I=imread('tire.tif');
imshow(I)
b1=uicontrol('parent',h0,...
    'units','points',...
    'tag','b1',...
    'backgroundcolor',[0.75 0.75 0.75],...
    'style','pushbutton',...
    'string','±ßÑØ²Ù×÷',...
    'position',[30 100 50 20],...
    'callback',[...
        'cla,',...
        'I=imread(''tire.tif'');,',...
        'f=inline(''max(x(:))'');,',...
        'I2=nlfilter(I,[2 2],f);,',...
        'imshow(I2)']);
b2=uicontrol('parent',h0,...
    'units','points',...
    'tag','b2',...
    'backgroundcolor',[0.75 0.75 0.75],...
    'style','pushbutton',...
    'string','ÏÔÊ¾¿é²Ù×÷',...
    'position',[100 100 50 20],...
    'callback',[...
        'cla,',...
        'I=imread(''tire.tif'');,',...
        'f=inline(''uint8(round(mean2(x)*ones(size(x))))'');,',...
        'I2=blkproc(I,[6 6],f);,',...
        'imshow(I2)']);
b3=uicontrol('parent',h0,...
    'units','points',...
    'tag','b3',...
    'backgroundcolor',[0.75 0.75 0.75],...
    'style','pushbutton',...
    'string','½»µþ¿é²Ù×÷',...
    'position',[170 100 50 20],...
    'callback',[...
        'cla,',...
        'I=imread(''tire.tif'');,',...
        'f=inline(''uint8(round(mean2(x)*ones(size(x))))'');,',...
        'I2=blkproc(I,[6 6],[3 3],f);,',...
        'imshow(I2)']);
b4=uicontrol('parent',h0,...
    'units','points',...
    'tag','b4',...
    'backgroundcolor',[0.75 0.75 0.75],...
    'style','pushbutton',...
    'string','¹Ø±Õ',...
    'fontsize',14,...
    'position',[90 50 70 30],...
    'callback','close');