h0=figure('toolbar','none',...
    'position',[200 150 450 250],...
    'name','ÊµÀý37');
[x,y]=meshgrid(-8:0.5:8);
r=sqrt(x.^2+y.^2)+eps;
z=sin(r)./r;
h0=mesh(x,y,z);
h1=axes('position',...
    [0.2 0.2 0.5 0.5],...
    'visible','off');
htext=uicontrol(gcf,...
    'units','points',...
    'position',[20 30 45 15],...
    'string','brightness',...
    'style','text');
hslider=uicontrol(gcf,...
    'units','points',...
    'position',[10 10 300 15],...
    'min',-1,...
    'max',1,...
    'style','slider',...
    'callback',...
    'brighten(get(hslider,''value''))');