h0=figure('toolbar','none',...
    'position',[198 56 350 468],... 
    'name','ÊµÀý78');
h1=axes('parent',h0,...
    'position',[0.25 0.45 0.5 0.5],...
    'visible','off');
load imdemos flower
imshow(flower)
colormap(copper)
n=size(X,1);
b1=uicontrol('parent',h0,...
    'units','points',...
    'tag','b1',...
    'style','pushbutton',...
    'string','ÂÖÀªÍ¼',...
    'backgroundcolor',[0.75 0.75 0.75],...
    'position',[30 100 50 20],...
    'callback',[...
        'cla,',...
        '[X,map]=imread(''flowers.tif'');,',...
        'X=double(flower);,',...
        'X=(0.25/256)*X;,',...
        'C=copper(35);,',...
        'set(gca,''colororder'',C(21:35,:),''box'',''on'');,',...
        'imcontour(X,3);,',...
        'axis([1 n 1 n]),',...
        'axis(''ij''),',...
        'axis(''square'')']);
b2=uicontrol('parent',h0,...
    'units','points',...
    'tag','b2',...
    'style','pushbutton',...
    'string','Î±²ÊÍ¼',...
    'backgroundcolor',[0.75 0.75 0.75],...
    'position',[100 100 50 20],...
    'callback',[...
        'cla,',...
        'D=-del2(X);,',...
        'pcolor(D),',...
        'axis([1 n 1 n]),',...
        'axis(''ij''),',...
        'shading(''flat'')']);
b3=uicontrol('parent',h0,...
    'units','points',...
    'tag','b3',...
    'style','pushbutton',...
    'string','3D±íÃæÍ¼',...
    'backgroundcolor',[0.75 0.75 0.75],...
    'position',[170 100 50 20],...
    'callback',[...
        'cla,',...
        'D=-del2(X);,',...
        'surf(X,D),',...
        'colormap(copper),',...
        'axis([1 n 1 n 0 1]),',...
        'axis(''ij''),',...
        'shading(''flat''),',...
        'view(-20,75);']);
b4=uicontrol('parent',h0,...
    'units','points',...
    'tag','b4',...
    'style','pushbutton',...
    'string','¹Ø±Õ',...
    'backgroundcolor',[0.75 0.75 0.75],...
    'position',[80 50 80 30],...
    'callback','close');
